package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/makrorof/gorm-graphql-postgres-echo-auth/internal/dto"
)

// Requests is the resolver for the requests field.
func (r *queryResolver) Requests(ctx context.Context) ([]*dto.ScanRequest, error) {
	panic(fmt.Errorf("not implemented: Requests - requests"))
}

// ScannedProducts is the resolver for the scannedProducts field.
func (r *queryResolver) ScannedProducts(ctx context.Context, requestID string, sortBy *dto.SortBy) ([]*dto.ScannedProductInfo, error) {
	panic(fmt.Errorf("not implemented: ScannedProducts - scannedProducts"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
